name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Pooler/Dockerfile --tag registry.bdlabs.org/pooler/pooler$(date +%s)
    - name: Push the docker Image
      run: docker push registry.bdlabs.org/pooler/pooler